name: Publish for .NET 8.0

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish single file
      run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true -o ./publish

    - name: List files in publish folder  # Verificar si el archivo existe
      run: ls -l ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish/*  # Asegúrate de subir los archivos correctos

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: published-app

    - name: List downloaded files
      run: ls -l ./WhichNumber  # Verificar qué se ha descargado

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: "Release ${{ github.run_number }}"
        tag: ${{ github.run_number }}
        body: "Archivo único publicado con .NET 8"
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./WhichNumber/*  # Apuntar al archivo en lugar de una carpeta
